### ISSUE TITLE
ncappc reports 2 Cmax values for same individual if concentration identical

### ISSUE THREAD

**Issue by Dstix** [UUPharmacometrics/ncappc#8]
When conducting NCA, one subject has identical concentration values at 1 and 4 hours, which also are the highest concentration in this subject. Is there a way to choose which value is chosen for Cmax (e.g. at the lowest or highest time)?

**Comment by cacha0227** [comment]
In case of multiple occurrence of the maximum concentration for an individual, this function automatically assigns Cmax to the latest time point (i.e. if the maximum concentration happens to be associated with T=1h and T=4, Cmax will be assigned to T=4h, hence Tmax will be 4h)

**Comment by Dstix** [comment]
Thanks, this answered my question.
